# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0407e8d3a46a7da80d6947417a0c60a777d2576dcd09779d4b889c86a7c4887077ebd9dfd43f676d3a65bb4fd48027730f92e679c73ec5a162b336571ea72692

test:
  secret_key_base: 8ee5257871a2fbba13fe7859afd28bc3a571ddd5538cbb579f91e684b28d51281b76b99dde6ad0a2bc2374234aff5b27e5857c36bdff1c4b27004f0037c0fdc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
